model_desc: Training model with 64 latent dim.
model_name: ae_1d
model_params:
  encoder_depth: 3
  decoder_depth: 3
  type: bert
lr: 1e-3
loss:
  type: bce
  hyper_params:
    kld_beta: 100
batch_size: 64
max_epochs: 100
max_steps: 5000
seed: 1
dataset:
  dataset_type: distance_vectors
  input_dir: /home/nikhilk/data/tfiih_superposed/distance_vectors
  output_dir: /home/nikhilk/dlintegrativemodels/runs/vae_encoder
  apply_sigmoid_input: True
  apply_padding: False
